CREATE TABLE [dbo].[catalogo_oferta_san_pablo] (
    [PRODUCTO]              VARCHAR (50)  NULL,
    [P_FARMACIA]            FLOAT (53)    NULL,
    [OFERTA]                FLOAT (53)    NULL,
    [COMERCIAL]             FLOAT (53)    NULL,
    [CONFIDENCIAL]          FLOAT (53)    NULL,
    [P_FINAL_SIN_IMPUESTOS] FLOAT (53)    NULL,
    [P_PUBLICO]             FLOAT (53)    NULL,
    [DESDE]                 VARCHAR (150) NULL,
    [HASTA]                 VARCHAR (150) NULL,
    [TIPO]                  VARCHAR (150) NULL,
    [CANT_BASE]             FLOAT (53)    NULL,
    [CANT_OFERTA]           FLOAT (53)    NULL,
    [SUCURSAL]              VARCHAR (150) NULL,
    [EX_SUCURSAL]           FLOAT (53)    NULL,
    [IMMOVC]                VARCHAR (150) NULL,
    [IMVOLC]                VARCHAR (255) NULL,
    [PGPDGR]                VARCHAR (255) NULL,
    [PGPPGR]                VARCHAR (255) NULL,
    [PGPGRP]                VARCHAR (255) NULL,
    [PGAGRP]                VARCHAR (150) NULL,
    [PGPCA1]                VARCHAR (150) NULL,
    [PGPCA2]                VARCHAR (255) NULL,
    [PGPCA3]                VARCHAR (150) NULL,
    [PGPCA4]                VARCHAR (255) NULL,
    [PGPCA5]                VARCHAR (255) NULL,
    [PGPCA6]                VARCHAR (150) NULL,
    [PGPRFA]                VARCHAR (255) NULL,
    [PGPRSE]                VARCHAR (255) NULL,
    [PGDESC]                VARCHAR (255) NULL,
    [MSMDEC]                VARCHAR (255) NULL,
    [EX_TOTAL]              FLOAT (53)    NULL,
    [PXTX50]                VARCHAR (255) NULL,
    [PJEANP]                VARCHAR (150) NULL,
    [CTPCT1]                VARCHAR (255) NULL,
    [CTPCT2]                VARCHAR (255) NULL,
    [CTPCT6]                VARCHAR (255) NULL,
    [DEVOLUCION]            VARCHAR (255) NULL,
    [DEV_DIAS_ANTES]        FLOAT (53)    NULL,
    [DEV_DIAS_DESPUES]      FLOAT (53)    NULL,
    [IVA]                   FLOAT (53)    NULL,
    [IEPS]                  FLOAT (53)    NULL,
    [PJPTQT]                FLOAT (53)    NULL,
    [PGCDAT]                FLOAT (53)    NULL,
    [NANSNA]                VARCHAR (255) NULL,
    [PGPHNCAT]              VARCHAR (255) NULL
);


GO

