CREATE TABLE [dbo].[cfd_parametros_estandar20130612] (
    [id_tarea]            INT            NOT NULL,
    [idcliente]           VARCHAR (10)   NULL,
    [sucursal]            INT            NULL,
    [descripcion]         VARCHAR (50)   NULL,
    [segto]               VARCHAR (2)    NULL,
    [ctepadre]            VARCHAR (20)   NULL,
    [habilitado]          BIT            NULL,
    [ftp]                 BIT            NULL,
    [correo]              BIT            NULL,
    [as2]                 BIT            NULL,
    [zip]                 BIT            NULL,
    [pdf]                 BIT            NULL,
    [archivo]             VARCHAR (50)   NULL,
    [direcciones]         VARCHAR (255)  NULL,
    [ftp_host]            VARCHAR (50)   NULL,
    [ftp_usuario]         VARCHAR (50)   NULL,
    [ftp_password]        VARCHAR (50)   NULL,
    [ftp_ruta_inbox]      VARCHAR (255)  NULL,
    [ftp_ruta_outbox]     VARCHAR (255)  NULL,
    [ftp_ruta_resp]       VARCHAR (255)  NULL,
    [as2_host]            VARCHAR (50)   NULL,
    [as2_usuario]         VARCHAR (50)   NULL,
    [as2_password]        VARCHAR (50)   NULL,
    [as2_ruta_inbox]      VARCHAR (255)  NULL,
    [as2_ruta_outbox]     VARCHAR (255)  NULL,
    [as2_ruta_resp]       VARCHAR (255)  NULL,
    [query]               VARCHAR (500)  NULL,
    [fecha_alta]          SMALLDATETIME  NULL,
    [periodo]             CHAR (1)       NULL,
    [clave_proveedor]     VARCHAR (20)   NULL,
    [mail_body]           VARCHAR (255)  NULL,
    [add_mailbody]        BIT            NULL,
    [nc]                  BIT            NULL,
    [sc]                  BIT            NULL,
    [brfc]                BIT            NULL,
    [rfc]                 CHAR (13)      NULL,
    [tarea]               INT            NULL,
    [ticket]              INT            NULL,
    [hora]                CHAR (4)       NULL,
    [renombrar]           BIT            NULL,
    [nc_c8]               BIT            NULL,
    [cuentas]             VARCHAR (1500) NULL,
    [archivo_xml_cliente] VARCHAR (50)   NULL
);


GO

