CREATE TABLE [dbo].[facturasMuguerza] (
    [sucursal]     TINYINT       NOT NULL,
    [factura]      CHAR (8)      NOT NULL,
    [serie]        CHAR (2)      NOT NULL,
    [cliente]      CHAR (5)      NOT NULL,
    [ruta]         CHAR (3)      NOT NULL,
    [facturado]    CHAR (1)      NULL,
    [farmacia]     CHAR (39)     NULL,
    [etiquetas]    CHAR (1)      NULL,
    [domicilio]    CHAR (40)     NULL,
    [colonia]      CHAR (23)     NULL,
    [itinerario]   CHAR (2)      NULL,
    [letradig]     CHAR (1)      NULL,
    [restodig]     CHAR (2)      NULL,
    [numdig]       CHAR (2)      NULL,
    [poblacion]    CHAR (15)     NULL,
    [jefeagente]   CHAR (1)      NULL,
    [numagente]    CHAR (2)      NULL,
    [control]      CHAR (1)      NULL,
    [diapago]      CHAR (1)      NULL,
    [cvecredito]   CHAR (1)      NULL,
    [filler2]      CHAR (2)      NULL,
    [password]     CHAR (4)      NULL,
    [horacap]      SMALLDATETIME NULL,
    [hojordsur]    CHAR (3)      NULL,
    [hojfactura]   CHAR (3)      NULL,
    [tipfac]       CHAR (1)      NULL,
    [bulto]        CHAR (1)      NULL,
    [producee0]    CHAR (4)      NULL,
    [renglonee0]   CHAR (4)      NULL,
    [importe]      CHAR (1)      NULL,
    [controlado]   CHAR (1)      NULL,
    [desctoesp]    CHAR (5)      NULL,
    [dueno]        CHAR (30)     NULL,
    [meno999]      CHAR (5)      NULL,
    [mayp000]      CHAR (5)      NULL,
    [encima]       CHAR (1)      NULL,
    [jaula]        CHAR (3)      NULL,
    [rutaf]        CHAR (3)      NULL,
    [facturadof]   CHAR (1)      NULL,
    [itineraf]     CHAR (3)      NULL,
    [producto3a]   CHAR (6)      NULL,
    [prducto2a]    CHAR (6)      NULL,
    [producto1a]   CHAR (6)      NULL,
    [productob]    CHAR (6)      NULL,
    [productoc]    CHAR (6)      NULL,
    [fechaprog]    SMALLDATETIME NULL,
    [repleon]      CHAR (4)      NULL,
    [limexcedid]   CHAR (1)      NULL,
    [impmenor]     CHAR (1)      NULL,
    [rutaencima]   CHAR (3)      NULL,
    [complerel]    CHAR (1)      NULL,
    [espnetos]     CHAR (1)      NULL,
    [mafnarch]     CHAR (8)      NULL,
    [prodimp]      CHAR (1)      NULL,
    [indcod]       CHAR (1)      NULL,
    [enestacion]   CHAR (3)      NULL,
    [numjob]       CHAR (3)      NULL,
    [puerta]       CHAR (2)      NULL,
    [filler3]      CHAR (1)      NULL,
    [tipoorden]    CHAR (1)      NULL,
    [tipofactur]   CHAR (1)      NULL,
    [cadenaid]     CHAR (1)      NULL,
    [modosepara]   CHAR (1)      NULL,
    [licitacion]   CHAR (16)     NULL,
    [contrato]     CHAR (16)     NULL,
    [orden]        CHAR (16)     NULL,
    [fianza]       CHAR (16)     NULL,
    [fechaalta]    SMALLDATETIME NULL,
    [noalta]       CHAR (10)     NULL,
    [segto]        CHAR (2)      NULL,
    [ctepadre]     CHAR (3)      NULL,
    [filler]       CHAR (13)     NULL,
    [timestamp]    DATETIME      NULL,
    [folio_fiscal] VARCHAR (8)   NULL,
    [fecha_tandem] SMALLDATETIME NULL,
    [ruta_factura] VARCHAR (MAX) NULL,
    [nomb_factura] VARCHAR (150) NULL,
    [msgWeb]       VARCHAR (500) NULL
);


GO

