CREATE TABLE [dbo].[facturacion_spt_fahorro] (
    [cedis]                         INT          NOT NULL,
    [remision]                      CHAR (8)     NOT NULL,
    [fecha_remision]                DATETIME     NULL,
    [cliente]                       CHAR (5)     NOT NULL,
    [tasa_iva]                      MONEY        NOT NULL,
    [sucursal_cte]                  VARCHAR (7)  NULL,
    [cte_estilo_ahorro]             VARCHAR (10) NOT NULL,
    [orden]                         INT          NULL,
    [codigo]                        CHAR (9)     NOT NULL,
    [cod_barras]                    VARCHAR (13) NULL,
    [descripcion]                   VARCHAR (30) NULL,
    [clas_fis]                      CHAR (2)     NULL,
    [cant_ped]                      INT          NOT NULL,
    [cant_ped_fahorro]              INT          NOT NULL,
    [cant_dev]                      INT          NULL,
    [tipo_reclamacion]              CHAR (2)     NULL,
    [porcentaje_fahorro]            MONEY        NULL,
    [porcentaje_marzam]             MONEY        NULL,
    [diferencia_porcentaje_oferta]  MONEY        NULL,
    [tipo_oferta]                   CHAR (2)     NULL,
    [ultimo_cambio_baan]            DATETIME     NULL,
    [ultimo_precio_notificado]      MONEY        NULL,
    [ultima_oferta_notificada]      MONEY        NULL,
    [prec_farm_marzam]              MONEY        NULL,
    [prec_farm_fahorro]             MONEY        NULL,
    [diferencia_precio]             MONEY        NULL,
    [importe_bruto_marzam]          MONEY        NULL,
    [importe_bruto_fahorro]         MONEY        NULL,
    [diferencia_importe_bruto]      MONEY        NULL,
    [importe_oferta_marzam]         MONEY        NULL,
    [importe_oferta_fahorro]        MONEY        NULL,
    [diferencia_importe_oferta]     MONEY        NULL,
    [importe_desc_com_marzam]       MONEY        NULL,
    [importe_desc_com_fahorro]      MONEY        NULL,
    [dif_importe_desc_com]          MONEY        NULL,
    [total_importe_neto_marzam]     MONEY        NULL,
    [total_iva_neto_marzam]         MONEY        NULL,
    [total_bonificacion_iva_marzam] MONEY        NULL,
    [total_marzam]                  MONEY        NULL,
    [importe_neto_fahorro]          MONEY        NULL,
    [pronto_pago_unitario]          MONEY        NULL,
    [iva_unitario]                  MONEY        NULL,
    [iva_neto_fahorro]              MONEY        NULL,
    [total_fahorro]                 MONEY        NULL,
    [diferencia_totales]            MONEY        NULL,
    [diferencia_importes_netos]     MONEY        NULL,
    [status_pedsok]                 CHAR (2)     NULL,
    [gestor_pedsok]                 CHAR (2)     NULL,
    [costo_pedsok]                  CHAR (2)     NULL,
    [oferta_pedsok]                 CHAR (2)     NULL,
    [pronto_pago_pedsok]            CHAR (2)     NULL,
    [iva_neto_pedsok]               CHAR (2)     NULL,
    [neto_pedsok]                   CHAR (2)     NULL,
    [monto_baan]                    MONEY        NULL,
    [tipo_pedido]                   VARCHAR (1)  NULL,
    [fecha_movimiento]              CHAR (2)     NULL,
    [pzas_pedidook]                 CHAR (2)     NULL,
    [Status]                        VARCHAR (15) NULL,
    [cuenta_estilo_baan]            VARCHAR (15) NULL,
    [bruto_menos_oferta_por_piezas] MONEY        NULL,
    [iva]                           MONEY        NULL,
    [descuento_comercial]           MONEY        NULL,
    [bonificacion_del_iva]          MONEY        NULL,
    [total2]                        MONEY        NULL,
    [reingresada_almacen]           VARCHAR (15) NULL
);


GO

