CREATE TABLE [dbo].[fanasa_tmp_pedidos_traductor] (
    [consecutivo]       BIGINT          NOT NULL,
    [sucursal]          TINYINT         NOT NULL,
    [cliente]           VARCHAR (5)     NOT NULL,
    [origen]            VARCHAR (1)     NOT NULL,
    [cod_cred]          VARCHAR (3)     NULL,
    [tipo_ped]          VARCHAR (5)     NULL,
    [ibs_orno]          BIGINT          NULL,
    [orden]             VARCHAR (16)    NULL,
    [licitacion]        VARCHAR (16)    NULL,
    [contrato]          VARCHAR (16)    NULL,
    [fianza]            VARCHAR (18)    NULL,
    [codigo]            VARCHAR (25)    NOT NULL,
    [cant_ped]          INT             NULL,
    [cant_surt]         INT             NULL,
    [prec_farm]         MONEY           NULL,
    [motivo_no_surtido] VARCHAR (50)    NULL,
    [archivo]           VARCHAR (15)    NULL,
    [fecha_pedido]      DATETIME        NULL,
    [fecha_respuesta]   DATETIME        NULL,
    [fecha_resp_tandem] DATETIME        NULL,
    [numero_linea]      INT             NULL,
    [numero_linea_resp] INT             NULL,
    [compania]          VARCHAR (12)    NULL,
    [NAOPNO]            NUMERIC (2)     NOT NULL,
    [NADEID]            CHAR (8)        NOT NULL,
    [NASTAT]            CHAR (1)        NOT NULL,
    [NANUM]             CHAR (11)       NOT NULL,
    [NANSNO]            CHAR (11)       NOT NULL,
    [NATYPP]            NUMERIC (1)     NOT NULL,
    [NANAME]            CHAR (30)       NOT NULL,
    [NAADR1]            CHAR (35)       NOT NULL,
    [NAADR2]            CHAR (35)       NOT NULL,
    [NAADR3]            CHAR (35)       NOT NULL,
    [NAADR4]            CHAR (35)       NOT NULL,
    [NAPOCD]            CHAR (16)       NOT NULL,
    [NANSNA]            CHAR (20)       NOT NULL,
    [NACREG]            CHAR (16)       NOT NULL,
    [NATREG]            CHAR (16)       NOT NULL,
    [NADUMM]            CHAR (1)        NOT NULL,
    [NACOUN]            CHAR (4)        NOT NULL,
    [NAAREA]            CHAR (3)        NOT NULL,
    [NALANG]            CHAR (3)        NOT NULL,
    [NANCA1]            CHAR (6)        NOT NULL,
    [NANCA2]            CHAR (6)        NOT NULL,
    [NANCA3]            CHAR (6)        NOT NULL,
    [NACRDT]            NUMERIC (8)     NOT NULL,
    [NAIORD]            CHAR (1)        NOT NULL,
    [NAPROD]            CHAR (1)        NOT NULL,
    [NAINNF]            NUMERIC (17, 3) NOT NULL,
    [NACNTY]            CHAR (5)        NOT NULL,
    [NASPCD]            CHAR (2)        NOT NULL,
    [NATAXJ]            CHAR (12)       NOT NULL,
    [NANANN]            NUMERIC (11)    NOT NULL,
    [NAMDCN]            CHAR (1)        NOT NULL,
    [NAPCDE]            CHAR (1)        NOT NULL,
    [NACTNB]            NUMERIC (19, 4) NOT NULL,
    [NAPROP]            NUMERIC (5, 2)  NOT NULL,
    [NACTNP]            NUMERIC (5, 2)  NOT NULL,
    [NAARHA]            CHAR (10)       NOT NULL,
    [NAAPHA]            CHAR (10)       NOT NULL,
    [NAISVC]            CHAR (1)        NOT NULL,
    [NANCA4]            CHAR (6)        NOT NULL,
    [NANCA5]            CHAR (6)        NOT NULL,
    [NANCA6]            CHAR (6)        NOT NULL
);


GO

