CREATE TABLE [dbo].[MXONAM] (
    [NANUM]    CHAR (11) NOT NULL,
    [NAMXNAME] CHAR (50) NOT NULL,
    [NAMXNSNA] CHAR (50) NOT NULL,
    [NAMXADR1] CHAR (50) NOT NULL,
    [NAMXADR2] CHAR (50) NOT NULL,
    [NAMXADR3] CHAR (50) NOT NULL
);


GO

