CREATE TABLE [dbo].[pedidos_klyns] (
    [sucursal]                 TINYINT      NULL,
    [cliente]                  VARCHAR (5)  NOT NULL,
    [cod_barras]               VARCHAR (13) NOT NULL,
    [cant_ped]                 INT          NOT NULL,
    [cant_surt]                INT          NULL,
    [motivo_no_surtido]        INT          NULL,
    [tamano_archivo_respuesta] MONEY        NULL,
    [codigo]                   VARCHAR (7)  NULL,
    [arch_cliente]             VARCHAR (50) NOT NULL,
    [arch_tandem]              VARCHAR (8)  NULL,
    [orden]                    VARCHAR (50) NOT NULL,
    [hash_md5]                 VARCHAR (50) NOT NULL,
    [fecha_pedido]             DATETIME     NOT NULL,
    [hora_resp_tandem]         DATETIME     NULL,
    [rftp]                     DATETIME     NULL,
    [tftp]                     DATETIME     NULL,
    [enviado_ftp]              CHAR (10)    NULL,
    [factura]                  VARCHAR (15) NULL,
    [codigo_farmacia]          VARCHAR (20) NULL,
    [eindicador]               CHAR (10)    NULL,
    [efecha]                   CHAR (10)    NULL,
    [esucursal]                CHAR (10)    NULL,
    [eordencompra]             VARCHAR (20) NULL,
    [eproveedor]               VARCHAR (20) NULL,
    [erenglones]               VARCHAR (20) NULL,
    [eimportesiva]             VARCHAR (50) NULL,
    [eimporteiva]              VARCHAR (50) NULL,
    [eimporteciva]             VARCHAR (50) NULL,
    [dindicador]               CHAR (10)    NULL,
    [drenglon]                 CHAR (10)    NULL,
    [drefklyns]                VARCHAR (20) NULL,
    [dprecio]                  MONEY        NULL,
    [dpordescto1]              MONEY        NULL,
    [dpordescto2]              MONEY        NULL,
    [dpordescto3]              MONEY        NULL,
    [dporoferta]               MONEY        NULL,
    [diva]                     MONEY        NULL,
    [dpreciounitsiva]          MONEY        NULL,
    [dimportesiva]             MONEY        NULL,
    [dimporteciva]             MONEY        NULL,
    [consecutivo]              BIGINT       NULL,
    [e_facsiva]                MONEY        NULL,
    [e_facciva]                MONEY        NULL,
    [e_iva]                    MONEY        NULL,
    [d_precio]                 MONEY        NULL,
    [d_procescto1]             MONEY        NULL,
    [d_poroferta]              MONEY        NULL,
    [d_iva]                    MONEY        NULL,
    [d_facsiva]                MONEY        NULL,
    [d_factciva]               MONEY        NULL,
    [total]                    MONEY        NULL
);


GO

