-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [sap].[spr_actualiza_facturas_smart]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	declare @tmpEEPlantilla table(
VWERK varchar(60),PARTNER varchar(60),XBLNR varchar(60),VBELN varchar(60),
FKDAT varchar(60),POSNR varchar(60),MATNR varchar(60),ARKTX varchar(60),
CHARG varchar(60),EAN11 varchar(60),KONDM varchar(60),CANTIDAD decimal(13,3),
PRECIOFARMACIA decimal(15,2),PRECIO_PUBLICO decimal(15,2),PRECIO_PUBLICO_IMP decimal(15,2),IMPORTE_BRUTO decimal(15,2),
PORCENTAJE_OFERTAS decimal(15,2),OFERTAS decimal(15,2),PORCENTAJE_DESCUENTOS  decimal(15,2),
DESCUENTOS decimal(15,2),IEPS  decimal(15,2),IVA  decimal(15,2),IMPORTE_NETO decimal(15,2),BSTKD varchar(60),
PORC_TMX1  decimal(15,2),PORC_TMX2  decimal(15,2),IND_SECTOR varchar(60),KNRZE varchar(60),TAXNUM varchar(60),
IDNUMBER varchar(60),ALTKN varchar(10),NAME_ORG1 varchar(60)
)  
	declare @fechaAux varchar(8)
set @fechaAux= convert(varchar,(CONVERT(datetime,getdate(),121)-1),112);
insert into @tmpEEPlantilla
exec [192.168.90.209].[MiddleWare].[IEmbarque].[ExtraccionEmbarquePlantillaFiltro] @fechaAux,'','','','RH'
insert into @tmpEEPlantilla
exec [192.168.90.209].[MiddleWare].[IEmbarque].[ExtraccionEmbarquePlantillaFiltro] @fechaAux,'','','','CG'

  ;with detalle_factura(Fila,[VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1])
		 as (
		 select ROW_NUMBER() OVER(PARTITION BY  [VWERK],[PARTNER],[VBELN],[POSNR],[MATNR] ORDER BY [MATNR] desc) AS Fila,[VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1] from @tmpEEPlantilla
		 )
		 SELECT [VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1]
		 INTO #detalle_factura
		 from detalle_factura WHERE Fila=1

	 MERGE [sap].[facturacion_fsmart_sap] AS T  
    USING (
	        SELECT [VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1]
			  FROM #detalle_factura
		   ) AS S  
	ON (T.[VWERK] = S.[VWERK] AND T.[PARTNER] = S.[PARTNER] AND T.[VBELN] = S.[VBELN] AND T.[POSNR] = S.[POSNR] AND T.[MATNR]= S.[MATNR])  
   
    WHEN NOT MATCHED THEN  
        INSERT ([VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1])  
        VALUES ([VWERK],[PARTNER],[XBLNR],[VBELN],[FKDAT],[POSNR],[MATNR],[ARKTX],[CHARG],[EAN11],[KONDM],[CANTIDAD],[PRECIOFARMACIA],[PRECIO_PUBLICO],[PRECIO_PUBLICO_IMP],[IMPORTE_BRUTO],[PORCENTAJE_OFERTAS],[OFERTAS],[PORCENTAJE_DESCUENTOS],[DESCUENTOS],[IEPS],[IVA],[IMPORTE_NETO],[BSTKD],[PORC_TMX1],[PORC_TMX2],[IND_SECTOR],[KNRZE],[TAXNUM],[IDNUMBER],[ALTKN],[NAME_ORG1]); 

		
END

GO

