USE monkeyland
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO

CREATE procedure [dbo].[usp_cxcice_documentos]
WITH ENCRYPTION
as
SELECT columnota FROM OPENQUERY(AS400,
'
SELECT 
SUBSTRING(TRIM(T1.ADNUM) || ''          '', 1, 10) || '';'' || --CLIENTE
RIGHT(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 12) || '';'' || --NUMERO DE DOCUMENTO
SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 7, 2) || ''/'' || SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 5, 2) || ''/'' || SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 1, 4) || '';'' || -- FECHA DEL DOCUMENTO
SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 7, 2) || ''/'' || SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 5, 2) || ''/'' || SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 1, 4) || '';'' || -- VENCIMIENTO DEL DOCUMENTO
LEFT(RIGHT(''                   '' || CAST(IFNULL(T3.DTSCOA, 0) AS VARCHAR(25)), 19), 18) || '';'' || --MONTO
''MXP'' || '';'' || --MONEDA
''  1.000'' || '';'' || --TIPO DE CAMBIO
''1'' || '';'' || --TIPO DE MOVIMIENTO NUEVO (1) MODIFICACION (2)
CASE
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''DMI'' AND SUBSTRING(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 1, 1) <> ''6'' THEN ''FAC''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''FKI'' THEN ''FAC''
WHEN SUBSTRING(T3.DTDOTY, 1, 1) = ''R''   THEN ''PAG''
WHEN SUBSTRING(T3.DTDOTY, 1, 1) = ''E''   THEN ''PAG''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''FKG'' THEN ''NCA''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''DMI'' AND SUBSTRING(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 1, 1) = ''6'' THEN ''FAC''
ELSE ''   '' END COLUMNOTA
FROM 
MA4620EF04.SRONAD T1 INNER JOIN MA4620EF04.SRONAM T2 ON T1.ADNUM = T2.NANUM AND T1.ADADNO = 1
INNER JOIN MA4620EF04.SRODTA T3 ON T1.ADNUM = T3.DTCUNO
INNER JOIN PASO.SC_SUCURSALES T17 ON T2.NAAREA = T17.IBS and T2.NACOUN = T17.PAIS AND SUBSTRING(T2.NANUM, 1, 1) = T17.IBS_LETRA
WHERE 
PASO.FN_ISNUMERIC(SUBSTRING(REPLACE(T1.ADNUM, '' '', ''''), 2,  5)) = 1 
UNION
SELECT 
SUBSTRING(TRIM(T1.ADNUM) || ''          '', 1, 10) || '';'' || --CLIENTE
RIGHT(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 12) || '';'' || --NUMERO DE DOCUMENTO
SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 7, 2) || ''/'' || SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 5, 2) || ''/'' || SUBSTRING(CAST(T3.DTVODT AS CHAR(8)), 1, 4) || '';'' || -- FECHA DEL DOCUMENTO
SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 7, 2) || ''/'' || SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 5, 2) || ''/'' || SUBSTRING(CAST(T3.DTDUDT AS CHAR(8)), 1, 4) || '';'' || -- VENCIMIENTO DEL DOCUMENTO
LEFT(RIGHT(''                   '' || CAST(IFNULL(T3.DTSCOA, 0) AS VARCHAR(25)), 19), 18) || '';'' || --MONTO
''MXP'' || '';'' || --MONEDA
''  1.000'' || '';'' || --TIPO DE CAMBIO
''1'' || '';'' || --TIPO DE MOVIMIENTO NUEVO (1) MODIFICACION (2)
CASE
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''DMI'' AND SUBSTRING(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 1, 1) <> ''6'' THEN ''FAC''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''FKI'' THEN ''FAC''
WHEN SUBSTRING(T3.DTDOTY, 1, 1) = ''R''   THEN ''PAG''
WHEN SUBSTRING(T3.DTDOTY, 1, 1) = ''E''   THEN ''PAG''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''FKG'' THEN ''NCA''
WHEN SUBSTRING(T3.DTDOTY, 1, 3) = ''DMI'' AND SUBSTRING(TRIM(CAST(T3.DTIDNO AS VARCHAR(25))), 1, 1) = ''6'' THEN ''FAC''
ELSE ''   '' END COLUMNOTA
FROM 
MA4620EF11.SRONAD T1 INNER JOIN MA4620EF11.SRONAM T2 ON T1.ADNUM = T2.NANUM AND T1.ADADNO = 1
INNER JOIN MA4620EF11.SRODTA T3 ON T1.ADNUM = T3.DTCUNO
INNER JOIN PASO.SC_SUCURSALES T17 ON T2.NAAREA = T17.IBS 
WHERE 
PASO.FN_ISNUMERIC(SUBSTRING(REPLACE(T1.ADNUM, '' '', ''''), 2,  5)) = 1 
')

GO
