
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE procedure [dbo].[usp_migra_devoluciones_spt_fahorro] 
WITH ENCRYPTION
as
insert into historica.dbo.devoluciones_spt_fahorro
select t1.DEVFA_SUCURSAL,
t1.DEVFA_FECHA_PROBLEMA,
t1.DEVFA_FOLIO_REMISION,
t1.DEVFA_CODIGO,
t1.DEVFA_ESTATUS,
t1.DEVFA_NUM_CUENTA,
t1.DEVFA_PEDIDO,
t1.DEVFA_REMISION,
t1.DEVFA_TIPO_RECLAMACION,
t1.DEVFA_CODIGO_BARRAS,
t1.DEVFA_PIEZAS_TEORICO,
t1.DEVFA_IMPORTE_FARMACIA,
t1.DEVFA_IMPORTE_OFERTA,
t1.DEVFA_IMPORTE_DESCTO_COM,
t1.DEVFA_IVA_TOTAL,
t1.DEVFA_GESTOR,
t1.DEVFA_AUTORIZACION,
t1.DEVFA_NUM_MOVIMIENTO,
t1.DEVFA_FECHA_INTERFASE,
t1.DEVFA_FILLER2,
t1.DEVFA_FECHA_FACTURA,
t1.DEVFA_FECHA_RECEPCION,
t1.DEVFA_FECHA_NOTA,
t1.DEVFA_FOLIO_DEVOL,
t1.DEVFA_PZAS_VENDIDAS,
t1.DEVFA_PZAS_ACEPTADAS,
t1.DEVFA_PZAS_MALESTADO,
t1.DEVFA_PZAS_SOBRANTES,
t1.DEVFA_PRECIO_COSTO,
t1.DEVFA_PRECIO_FARMACIA,
t1.DEVFA_DESCTO_COMER_CTE,
t1.DEVFA_PZAS_OFERTA,
t1.DEVFA_CANTIDAD_BASE,
t1.DEVFA_CANTIDAD_OFERTA,
t1.DEVFA_PORCENTAJE_OFERTA,
t1.DEVFA_IMPORTE_DEVOL_REAL,
t1.DEVFA_IMPORTE_OFERTA_REAL,
t1.DEVFA_IMPORTE_DESCTO_COM_REAL,
t1.DEVFA_CLASIF_FISCAL,
t1.DEVFA_DESCTO_COMER_PROD,
t1.DEVFA_IMPORTE_IVA,
t1.DEVFA_IMPORTE_NETO,
t1.DEVFA_FECHA_INTERFASE_REAL,
t1.DEVFA_CANT_FALTANTE_FACT,
t1.DEVFA_IMPORTE_FOLIO_FACT,
t1.DEVFA_FILLER1
 from devoluciones_spt_fahorro t1 left outer join historica.dbo.devoluciones_spt_fahorro t2 on
t1.devfa_sucursal = t2.devfa_sucursal and
t1.devfa_folio_remision = t2.devfa_folio_remision and
t1.devfa_codigo = t2.devfa_codigo and
t1.DEVFA_NUM_CUENTA = t2.DEVFA_NUM_CUENTA and
t1.DEVFA_TIPO_RECLAMACION = t2.DEVFA_TIPO_RECLAMACION
where t2.devfa_sucursal is null and t1.devfa_codigo is not null
GO
