
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO



CREATE procedure [dbo].[usp_cxcice_clientes]

as
SELECT columnota FROM OPENQUERY(AS400,
'SELECT 
SUBSTRING(T2.NANCA1 || ''     '', 3, 4) || '';'' || --NUMERO DE GRUPO (CTEPADRE)
SUBSTRING(TRIM(T1.ADNUM) || ''          '', 1, 10) || '';'' || --CLIENTE
SUBSTRING(TRIM(T1.ADMXNAME) || ''                                                  '', 1, 50) || '';'' || --NOMBRE DEL CLIENTE
SUBSTRING(T1.ADMXADR2 || ''          '', 1, 15) ||  --CALLE
SUBSTRING(T1.ADMXEXT1 || ''          '', 1, 5) ||  --NUMERO EXTERIOR
SUBSTRING(T1.ADMXNEIB || ''          '', 1, 10) || '';'' || --COLONIA
SUBSTRING(T1.ADMXCITY || ''                              '', 1, 30) || '';'' || --DELEGACION MUNICIPIO
IFNULL(T18.CLAVE, ''   '') || '';'' || --ESTADO
''MX                  '' || '';'' || --PAIS
''ESP'' || '';'' || --IDIOMA
''MXP'' COLUMNOTA --MONEDA
FROM 
MA4620EF04.MXONAD T1 INNER JOIN MA4620EF04.SRONAM T2 ON T1.ADNUM = T2.NANUM AND T1.ADADNO = 1
INNER JOIN MA4620EF04.SROCMA T4 ON T2.NANUM = T4.CMCUNO
LEFT OUTER JOIN MA4620EF04.SROCRP T5 ON T4.CMCPRO = T5.CPCPRO
INNER JOIN PASO.SC_SUCURSALES T17 ON T2.NAAREA = T17.IBS and T2.NACOUN = T17.PAIS AND SUBSTRING(T2.NANUM, 1, 1) = T17.IBS_LETRA
LEFT OUTER JOIN PASO.SC_ESTADOS T18 ON T1.ADMXSTTE = T18.DESCRIPCION
WHERE 
PASO.FN_ISNUMERIC(SUBSTRING(REPLACE(T1.ADNUM, '' '', ''''), 2,  5)) = 1 
UNION
SELECT 
SUBSTRING(T2.NANCA1 || ''     '', 3, 4) || '';'' || --NUMERO DE GRUPO (CTEPADRE)
SUBSTRING(TRIM(T1.ADNUM) || ''          '', 1, 10) || '';'' || --CLIENTE
SUBSTRING(TRIM(T1.ADMXNAME) || ''                                                  '', 1, 50) || '';'' || --NOMBRE DEL CLIENTE
SUBSTRING(T1.ADMXADR2 || ''          '', 1, 15) ||  --CALLE
SUBSTRING(T1.ADMXEXT1 || ''          '', 1, 5) ||  --NUMERO EXTERIOR
SUBSTRING(T1.ADMXNEIB || ''          '', 1, 10) || '';'' || --COLONIA
SUBSTRING(T1.ADMXCITY || ''                              '', 1, 30) || '';'' || --DELEGACION MUNICIPIO
IFNULL(T18.CLAVE, ''   '') || '';'' || --ESTADO
''MX                  '' || '';'' || --PAIS
''ESP'' || '';'' || --IDIOMA
''MXP'' COLUMNOTA --MONEDA
FROM 
MA4620EF11.MXONAD T1 INNER JOIN MA4620EF11.SRONAM T2 ON T1.ADNUM = T2.NANUM AND T1.ADADNO = 1
INNER JOIN MA4620EF11.SROCMA T4 ON T2.NANUM = T4.CMCUNO
LEFT OUTER JOIN MA4620EF11.SROCRP T5 ON T4.CMCPRO = T5.CPCPRO
INNER JOIN PASO.SC_SUCURSALES T17 ON T2.NAAREA = T17.IBS 
LEFT OUTER JOIN PASO.SC_ESTADOS T18 ON T1.ADMXSTTE = T18.DESCRIPCION
WHERE 
PASO.FN_ISNUMERIC(SUBSTRING(REPLACE(T1.ADNUM, '' '', ''''), 2,  5)) = 1 
')

GO
